import { useEffect, useState } from "react";
import type { CSSProperties, FormEvent, ReactNode } from "react";
import "./App.css";

type Category = { id: number; title: string; icon: string; color: string; description: string };
type Post = { board: string; title: string; author: string; count: number; time: string };
type Member = { id: number; username: string; nickname: string; email?: string };
type View = "home" | "free" | "login" | "signup" | "mypage";

const AUTH_API = `${window.location.hostname === "127.0.0.1" ? "http://127.0.0.1:8080" : "http://localhost:8080"}/api/auth`;
const MEMBER_CACHE_KEY = "lounge-member";
const categories: Category[] = [
  { id: 1, title: "자유 게시판", icon: "💬", color: "#32cd32", description: "자유로운 이야기" }, { id: 2, title: "게임 게시판", icon: "🎮", color: "#7c3aed", description: "게임 소식과 잡담" }, { id: 3, title: "공략 게시판", icon: "📘", color: "#16a39a", description: "팁 · 공략 · 정보" }, { id: 4, title: "질문 게시판", icon: "❔", color: "#ea8b27", description: "질문과 답변" }, { id: 5, title: "거래 게시판", icon: "🛒", color: "#22a65f", description: "아이템 · 계정 거래" }, { id: 6, title: "스크린샷", icon: "🖼️", color: "#e9506d", description: "인증 · 자랑 · 기록" },
];
const hotPosts: Post[] = [{ board: "자유 게시판", title: "오늘 업데이트 이후 체감 어떤가요?", author: "라운저", count: 42, time: "12:48" }, { board: "게임 게시판", title: "이번 주 이벤트 보상 정리해봤습니다", author: "겜잘알", count: 31, time: "12:15" }, { board: "공략 게시판", title: "초보자가 먼저 챙기면 좋은 세팅 모음", author: "공략러", count: 28, time: "11:43" }];
const recommendedPosts: Post[] = [{ board: "공략 게시판", title: "자주 묻는 질문 한 번에 보기", author: "관리자", count: 16, time: "어제" }, { board: "거래 게시판", title: "거래 전 꼭 확인해야 할 체크리스트", author: "안전거래", count: 14, time: "어제" }, { board: "게임 게시판", title: "이번 시즌 주요 변경점 요약", author: "소식통", count: 12, time: "월요일" }];

function readView(): View { const p = new URLSearchParams(window.location.search); if (p.get("board") === "free") return "free"; const page = p.get("page"); return page === "login" || page === "signup" || page === "mypage" ? page : "home"; }
function getCachedMember(): Member | null { try { const saved = localStorage.getItem(MEMBER_CACHE_KEY); return saved ? JSON.parse(saved) as Member : null; } catch { return null; } }

function Header({ onHome, onLogin, onSignup, onMyPage, member, onLogout }: { onHome: () => void; onLogin: () => void; onSignup: () => void; onMyPage: () => void; member: Member | null; onLogout: () => void }) {
  return <header className="header"><button className="logo logoButton" onClick={onHome}><img className="brandLogo" src="/brand/lounge-logo.png" alt="" /><span>LOUNGE</span><small>COMMUNITY</small></button><form className="searchBox" onSubmit={(event) => event.preventDefault()}><input type="search" aria-label="게시판 검색" placeholder="게시판, 글, 유저를 검색해보세요" /><button aria-label="검색">⌕</button></form><div className="userActions">{member ? <><span className="memberGreeting"><b>{member.nickname}</b>님</span><button className="myPageBtn" onClick={onMyPage}>마이페이지</button><button className="loginBtn" onClick={onLogout}>로그아웃</button></> : <><button className="loginBtn" onClick={onLogin}>로그인</button><button className="joinBtn" onClick={onSignup}>회원가입</button></>}</div></header>;
}
function PostList({ posts, onOpenFree }: { posts: Post[]; onOpenFree?: () => void }) { return <ul className="postList">{posts.map((post) => <li key={post.title}><span className="boardName">{post.board}</span><button className="postLink" onClick={post.board === "자유 게시판" ? onOpenFree : undefined}>{post.title}</button><span className="postMeta">{post.author} · <b>{post.count}</b> · {post.time}</span></li>)}</ul>; }

function Home({ onOpenFree, header }: { onOpenFree: () => void; header: ReactNode }) { return <>{header}<main className="main"><section className="categorySection"><div className="sectionHeading"><div><span className="eyebrow">BOARD DIRECTORY</span><h2>모든 게시판</h2></div><span>관심 있는 커뮤니티를 찾아보세요</span></div><div className="categoryGrid">{categories.map((category) => <button className={`categoryCard ${category.id !== 1 ? "comingSoon" : ""}`} key={category.id} style={{ "--point-color": category.color } as CSSProperties} onClick={category.id === 1 ? onOpenFree : undefined}><span className="categoryIcon">{category.icon}</span><span><b>{category.title}</b><small>{category.id === 1 ? "새 탭에서 게시판 입장" : `${category.description} · 준비 중`}</small></span><i>{category.id === 1 ? "↗" : "·"}</i></button>)}</div></section><div className="contentGrid homeBoards"><section className="boardPanel hotPanel"><div className="panelHeading"><div><span className="hotDot">●</span><h2>핫 게시판</h2><p>지금 가장 활발한 이야기</p></div><button className="textButton" onClick={onOpenFree}>더보기 →</button></div><PostList posts={hotPosts} onOpenFree={onOpenFree} /></section><aside className="sidePanels"><section className="boardPanel"><div className="panelHeading"><div><h2>추천 게시판</h2><p>놓치기 아쉬운 글</p></div><span>더보기 →</span></div><PostList posts={recommendedPosts} /></section><section className="notice"><span>📣</span><div><b>자유 게시판 오픈</b><p>첫 번째 게시판을 둘러보고 이야기를 나눠보세요.</p></div><button onClick={onOpenFree}>입장</button></section></aside></div><section className="boardPanel latestPanel"><div className="panelHeading"><div><h2>새로운 게시글</h2><p>방금 올라온 커뮤니티 이야기</p></div><div className="tabs"><button className="selected">전체</button><button>자유</button><button>질문</button><button>정보</button></div></div><PostList posts={[...hotPosts, ...recommendedPosts.slice(0, 2)]} /></section></main></>; }

function FreeBoard({ onHome, header }: { onHome: () => void; header: ReactNode }) { const posts = ["[안내] 자유 게시판 이용 수칙", "[공지] 커뮤니티 업데이트 및 개선 예정 안내", "오늘 업데이트 이후 체감 어떤가요?", "복귀 유저인데 지금 시작해도 괜찮나요?", "이번 주 이벤트 보상 정리해봤습니다", "초보자가 먼저 챙기면 좋은 세팅 모음"]; return <>{header}<main className="main boardPage"><div className="breadcrumbs"><button onClick={onHome}>홈</button><span>›</span><span>자유 게시판</span></div><section className="boardHero"><div><span className="boardHeroIcon">💬</span><div><span className="eyebrow">FREE BOARD</span><h1>자유 게시판</h1><p>게임, 일상, 질문, 정보까지 자유롭게 이야기를 나누는 공간</p></div></div><button className="writeButton">✎ 글쓰기</button></section><section className="boardTabs"><button className="selected">전체</button><button>잡담</button><button>질문</button><button>정보</button><button>공략</button><button>인증</button></section><div className="boardLayout"><section className="boardTable"><div className="tableTools"><b>전체 글 <strong>3,812</strong></b><div><button className="sortSelected">최신순</button><button>추천순</button><button>조회순</button></div></div><div className="tableHead"><span>번호</span><span>제목</span><span>글쓴이</span><span>작성일</span><span>조회</span><span>추천</span></div>{posts.map((title, index) => <article className={`postRow ${index < 2 ? "noticeRow" : ""}`} key={title}><span>{index < 2 ? "공지" : 3814 - index}</span><a href="#post">{index > 1 && <em>{index === 3 ? "질문" : "잡담"}</em>}{title}<small> [{42 - index * 3}]</small></a><span>{index < 2 ? "운영자" : "라운저"}</span><span>{index < 2 ? "2026.06.23" : "12:48"}</span><span>{326 - index * 16}</span><span>{42 - index * 3}</span></article>)}<div className="pagination"><button>‹</button><button className="current">1</button><button>2</button><button>3</button><button>›</button></div></section><aside className="boardAside"><section><h2>자유 게시판 인기글</h2><ol><li>이번 시즌 주요 변경점 요약</li><li>복귀 유저를 위한 시작 가이드</li><li>오늘의 인기 스크린샷</li><li>초보자가 자주 묻는 질문</li><li>거래 전 확인할 체크리스트</li></ol></section><section className="asideNotice"><b>처음 오셨나요?</b><p>게시판 이용 수칙을 확인하고 즐겁게 참여해 주세요.</p><a href="#guide">이용 안내 보기 →</a></section></aside></div></main></>; }
async function errorMessage(response: Response) { const body = await response.json().catch(() => ({})); return body.detail || body.message || "요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요."; }

function AuthPage({ mode, header, onComplete, onCancel, onAlternate }: { mode: "login" | "signup"; header: ReactNode; onComplete: (member: Member) => void; onCancel: () => void; onAlternate: () => void }) {
  const isSignup = mode === "signup"; const [username, setUsername] = useState(""); const [nickname, setNickname] = useState(""); const [email, setEmail] = useState(""); const [emailError, setEmailError] = useState(""); const [password, setPassword] = useState(""); const [passwordConfirm, setPasswordConfirm] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const validateEmail = (value: string) => { const valid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value); setEmailError(valid ? "" : "정확한 형식으로 이메일을 입력하세요."); return valid; };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); if (isSignup && !validateEmail(email)) return; if (isSignup && password !== passwordConfirm) { setError("비밀번호 확인이 일치하지 않습니다."); return; } setSubmitting(true); try { const response = await fetch(`${AUTH_API}/${isSignup ? "signup" : "login"}`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(isSignup ? { username, nickname, email, password } : { username, password }) }); if (!response.ok) { setError(await errorMessage(response)); return; } if (isSignup) { onAlternate(); return; } onComplete(await response.json()); } catch { setError("서버에 연결하지 못했습니다. 백엔드가 실행 중인지 확인해 주세요."); } finally { setSubmitting(false); } };
  return <>{header}<main className="authMain"><section className="authCard"><img className="authLogo" src="/brand/lounge-logo.png" alt="LOUNGE" /><span className="eyebrow">LOUNGE COMMUNITY</span><h1>{isSignup ? "회원가입" : "로그인"}</h1><p>{isSignup ? "새 계정을 만들고 커뮤니티에 참여해 보세요." : "계정으로 로그인하고 커뮤니티를 이용하세요."}</p><form className="authForm" onSubmit={submit}><label>아이디<input value={username} onChange={(event) => setUsername(event.target.value)} placeholder="영문, 숫자 7자 이상" autoComplete="username" required minLength={7} maxLength={30} pattern="[A-Za-z0-9]{7,30}" title="아이디는 영문과 숫자 7~30자로 입력해 주세요." /></label>{isSignup && <><label>닉네임<input value={nickname} onChange={(event) => setNickname(event.target.value)} placeholder="2~30자" autoComplete="nickname" required minLength={2} maxLength={30} /></label><label>이메일<input type="email" value={email} onChange={(event) => { setEmail(event.target.value); if (emailError) validateEmail(event.target.value); }} onBlur={(event) => validateEmail(event.target.value)} onInvalid={(event) => event.currentTarget.setCustomValidity("정확한 형식으로 이메일을 입력하세요.")} onInput={(event) => event.currentTarget.setCustomValidity("")} placeholder="example@email.com" autoComplete="email" required maxLength={254} />{emailError && <span className="fieldError">{emailError}</span>}</label></>}<label>비밀번호{isSignup ? <input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="8자 이상 입력하세요" autoComplete="new-password" required minLength={8} maxLength={72} /> : <span className="passwordInput"><input type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="8자 이상 입력하세요" autoComplete="current-password" required minLength={8} maxLength={72} /><button type="button" className="passwordToggle" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "비밀번호 숨기기" : "비밀번호 보기"}>👁</button></span>}</label>{isSignup && <label>비밀번호 확인<input type="password" value={passwordConfirm} onChange={(event) => setPasswordConfirm(event.target.value)} placeholder="비밀번호를 한 번 더 입력하세요" autoComplete="new-password" required /></label>}{error && <p className="authError">{error}</p>}{isSignup ? <div className="authActions"><button type="button" className="authCancel" onClick={onCancel}>취소</button><button className="authSubmit" disabled={submitting}>가입하기</button></div> : <button className="authSubmit" disabled={submitting}>{submitting ? "처리 중..." : "로그인"}</button>}</form><p className="authSwitch">{isSignup ? "이미 계정이 있으신가요?" : "아직 계정이 없으신가요?"} <button onClick={onAlternate}>{isSignup ? "로그인" : "회원가입"}</button></p><p className="authSecurity">비밀번호는 BCrypt 단방향 해시로 안전하게 저장됩니다.</p></section></main></>;
}

function MyPage({ member, header }: { member: Member; header: ReactNode }) { const [saved, setSaved] = useState(false); return <>{header}<main className="main myPage"><div className="breadcrumbs"><span>홈</span><span>›</span><span>마이페이지</span></div><section className="myPageGrid"><section className="myProfileCard"><div className="profileBadge">{member.nickname.slice(0, 1)}</div><div><span className="eyebrow">MY LOUNGE</span><h1>{member.nickname}님의 라운지</h1><p>{member.username} · {member.email || "이메일 미등록"}</p></div></section><section className="mySettingsCard"><div className="panelHeading"><div><h2>커뮤니티 설정</h2><p>나에게 맞는 라운지를 설정하세요</p></div></div><form onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><label>관심 게시판<select defaultValue="자유 게시판"><option>자유 게시판</option><option>게임 게시판</option><option>공략 게시판</option></select></label><label className="checkLabel"><input type="checkbox" defaultChecked /> 인기글 알림 받기</label><label className="checkLabel"><input type="checkbox" defaultChecked /> 내 글의 댓글 알림 받기</label><button className="authSubmit">설정 저장</button>{saved && <p className="settingsSaved">설정이 저장되었습니다.</p>}</form></section></section><section className="myActivity"><h2>나의 활동</h2><div><strong>0</strong><span>작성한 글</span></div><div><strong>0</strong><span>받은 댓글</span></div><div><strong>0</strong><span>북마크</span></div></section></main></>; }

function App() {
  const [view, setView] = useState<View>(readView); const [member, setMember] = useState<Member | null>(getCachedMember); const [notice, setNotice] = useState("");
  const navigate = (next: View, replace = false) => { const url = new URL(window.location.href); url.search = ""; if (next === "free") url.searchParams.set("board", "free"); if (next === "login" || next === "signup" || next === "mypage") url.searchParams.set("page", next); window.history[replace ? "replaceState" : "pushState"]({ view: next }, "", url); setView(next); };
  const updateMember = (next: Member | null) => { setMember(next); if (next) localStorage.setItem(MEMBER_CACHE_KEY, JSON.stringify(next)); else localStorage.removeItem(MEMBER_CACHE_KEY); };
  useEffect(() => { const onPopState = () => setView(readView()); window.addEventListener("popstate", onPopState); return () => window.removeEventListener("popstate", onPopState); }, []);
  useEffect(() => { fetch(`${AUTH_API}/me`, { credentials: "include" }).then((response) => response.ok ? response.json() : null).then((data) => { updateMember(data); if (data && (readView() === "login" || readView() === "signup")) navigate("home", true); }).catch(() => undefined); }, []);
  const openFree = () => window.open(`${window.location.pathname}?board=free`, "_blank", "noopener,noreferrer"); const logout = async () => { await fetch(`${AUTH_API}/logout`, { method: "POST", credentials: "include" }).catch(() => undefined); updateMember(null); navigate("home", true); };
  const header = <Header onHome={() => navigate("home")} onLogin={() => navigate("login")} onSignup={() => navigate("signup")} onMyPage={() => member ? navigate("mypage") : navigate("login")} member={member} onLogout={logout} />;
  if (view === "login" || view === "signup") return <div className="app"><AuthPage mode={view} header={header} onComplete={(loggedIn) => { updateMember(loggedIn); navigate("home", true); }} onCancel={() => navigate("home")} onAlternate={() => { if (view === "signup") { setNotice("회원가입이 완료되었습니다. 로그인해 주세요."); navigate("login", true); } else navigate("signup"); }} />{notice && <div className="authToast">{notice}</div>}</div>;
  if (view === "mypage" && member) return <div className="app"><MyPage member={member} header={header} /><Footer /></div>;
  return <div className="app">{view === "free" ? <FreeBoard onHome={() => navigate("home")} header={header} /> : <Home onOpenFree={openFree} header={header} />}<Footer /></div>;
}
function Footer() { return <footer className="footer"><strong>LOUNGE COMMUNITY</strong><span>좋아하는 주제로 모이고 이야기하는 공간</span><span>© LOUNGE. All rights reserved.</span></footer>; }
export default App;
